config/routes.rb
Rails.application.routes.draw do
  mount RailsEventStore::Browser => '/res' if Rails.env.development?
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  root 'leave_requests#index'

  resources :leave_requests, only: [:show, :index, :new] do
    collection do
      post :submit, to: 'leave_requests#submit'
    end
    member do
      post :change_duration
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def event_store
    Rails.configuration.event_store
  end

  def command_bus
    Rails.configuration.command_bus
  end
end

app/controllers/leave_requests_controller.rb
class LeaveRequestsController < ApplicationController
  def index
    @requests = Leaves::Request.all
  end

  def show
    @request = Leaves::Request.find_by(uid: params[:id])
    @dates = Leaves::Date.where(request_uid: params[:id])
  end

  def new
    @leave_request_id = SecureRandom.uuid
    @employees = [OpenStruct.new(name: 'Dung Bui', id: '123')]
    @categories = [OpenStruct.new(name: 'Annual leave', id: '123')]
  end

  def submit
    leave_dates = params[:leave_dates].map { |ld| Leave::Date.new(date: ld[:date], hours: ld[:hours].to_f) }
    duration = Leave::Duration.from_range(date_range: params[:duration])
    command = Leave::SubmitRequest.new(request_id: params[:leave_request_id], duration: duration,
                                       category_id: params[:category_id].to_i, employee_id: params[:employee_id].to_i,
                                       leave_dates: leave_dates)
    command_bus.(command)
    redirect_to leave_request_path(command.request_id)
  end

  def change_duration
    duration = Leave::Duration.new(from: params[:from], to: params[:to])
    new_dates = Leave::DatesGenerator.new(duration: duration).call

    render json: new_dates
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mapmap</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
  </head>
  <body>
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/leave_requests/index.html.erb
<h1>Leave Requests</h1>
<%= link_to 'New Leave Requests', new_leave_request_path, class: "btn btn-primary" %>

<br/>
<br/>
<table class="table">
  <thead>
    <tr>
      <th>Number</th>
      <th>Employee</th>
      <th>Category</th>
      <th>Status</th>
      <th>Duration</th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= link_to request.id, leave_request_path(request.uid) %></td>
        <td><%= request.employee %></td>
        <td><%= request.category %></td>
        <td><%= request.status %></td>
        <td><%= request.duration.to_s %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/leave_requests/new.html.erb
<h1>New Requests</h1>

<%= form_tag(submit_leave_requests_path, method: "post") do %>
  <%= hidden_field_tag(:leave_request_id, @leave_request_id) %>
  <p>Employee:
    <%= select_tag(:employee_id, options_from_collection_for_select(@employees, :id, :name)) %>
  </p>
  <p>Category:
    <%= select_tag(:category_id, options_from_collection_for_select(@categories, :id, :name)) %>
  </p>
  <p>Duration:
    <input type='text' name='duration' class='duration' />
  </p>
  <div style='display: none' class='leave_dates'>
    <p>Dates:</p>
    <div class='leave_dates_list' style='margin: 0 0 15px 15px'>
    </div>
  </div>

  <%= submit_tag("Submit", class: "btn btn-primary") %>
  <%= link_to 'Back', leave_requests_path, class: "btn btn-default" %>
<% end %>

<script>
  $(function() {
    $('input.duration').daterangepicker({
      "locale": {
        "format": "DD/MM/YYYY"
      }
    }, function(start, end, label) {
      $.ajax(
        {
          'url': '<%= escape_javascript(change_duration_leave_request_url(id: @leave_request_id)) %>',
          'data': {
            'from': start.format('DD/MM/YYYY'),
            'to': end.format('DD/MM/YYYY'),
            'authenticity_token': '<%= form_authenticity_token %>'
          },
          'method': 'POST',
          'success': function(data) {
            $('.leave_dates').show()
            $('.leave_dates_list').empty()
            data.forEach(function(leave_date) {
              dateInput = document.createElement('input')
              dateInput.value = leave_date['date']
              dateInput.name = 'leave_dates[][date]'
              dateInput.type = 'text'
              dateInput.style = 'pointer-events:none'
              hoursInput = document.createElement('input')
              hoursInput.value = leave_date['hours']
              hoursInput.name = 'leave_dates[][hours]'
              hoursInput.type = 'number'
              hoursInput.step = 0.1
              newItem = document.createElement('div')
              newItem.append(dateInput, ": ", hoursInput, " hours")
              $('.leave_dates_list').append(newItem)
            })
          }
        }
      )
    });
  });
</script>

app/views/leave_requests/show.html.erb
<h1>Leave Request: <%= @request.id %></h1>
<p>
Employee: <%= @request.employee %><br/>
Category: <%= @request.category %><br/>
Status: <%= @request.status %><br/>
Duration: <%= @request.duration.to_s %><br/>
Total hours: <%= @request.total_hours.round(2) %><br/>
</p>

<h2>Leave Dates:</h2>

<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Hours</th>
    </tr>
  </thead>

  <tbody>
  <% @dates.each do |date| %>
    <tr>
    <td><%= date.date.to_s(:dmy) %></td>
    <td><%= date.hours.round(2) %></td>
  </tr>
<% end %>
  </tbody>
</table>

<%= link_to 'Back', leave_requests_path, class: "btn btn-default" %>